### ISSUE TITLE
A bit of last minute help please :)

### ISSUE THREAD

**Issue by char1129** [char1129/saas-website#3]
@muxlowc @mackenzierose @char1129 

Hello Ladies,
I am getting a few weird errors with my code that seem to repeat throughout the document. I've been stuck on trying to resolve these for quite a while and have changed my code around a bit a few times to see if I could find a happy middle ground between my drop-down menu (I think the cause) and Markbot to little avail. Your suggestions? (see attached images) Also I am getting the same error as Holly in regards to the  Main link focus (just on one page, which is confusing). 
I'll keep on trucking tomorrow on this issue and add more flourish to my sight as I go in-case there is nothing that can be done about them.

Thank you ladies! If I don't get the chance to say so later on, have a wonderful summer and stay healthy.
See you hopefully in the halls - next school year.

Sarah

![help1](https://user-images.githubusercontent.com/55107755/79838100-7f1ed100-8380-11ea-80d0-e1ce60f601ff.JPG)
![help2](https://user-images.githubusercontent.com/55107755/79838103-7fb76780-8380-11ea-8ac2-a1fff5eaa343.JPG)

**Comment by muxlowc** [comment]
@char1129  hmm yes it's definitely because of your nav sitting in the burger button.  I think since you have display none on your "dropdown-content" markbot thinks it doesn't really exist, hence all of the error messages. I don't think there is really a fix to make markbot happy, mostly because markbot wasn't really set up for a burger nav. That being said, you can ignore these messages if the nav is working the way you want, and just write in your Request for Grade that you made the decision to build it differently + attach a screenshot of your markbot when you submit :)

**Comment by char1129** [comment]
Thank you! <3
